version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=order-management-backend-db-1
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=order_db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
